### ISSUE TITLE
Translate the README into Spanish

### ISSUE THREAD

**Issue by pangolp** [masterking32/WoW-Server-Relay#1]
I open this issue, more than anything, so as not to forget. Then, I will create the corresponding pull request, with the Spanish translation (if it helps). I'm waiting to see if I believe it or not. I already made the fork.

**Comment by masterking32** [comment]
Hello, that's great! You can create the file and then submit a pull request. Please create a file named `Spanish.md` inside the `docs` folder.

**Comment by pangolp** [comment]
> Hello, that's great! You can create the file and then submit a pull request. Please create a file named `Spanish.md` inside the `docs` folder.

Perfect. I will do it soon.

**Comment by masterking32** [comment]
Please ensure that you translate the most recent version of the README.md file, as it has been updated. Thank you.

**Comment by pangolp** [comment]
> Please ensure that you translate the most recent version of the README.md file, as it has been updated. Thank you.

If you want, let me know when I finish it and then I'll do the translation. I can wait for you to finish it, I'm in no rush to create the document. What's more, I didn't even read what it's really about hahaha. I am only interested in collaborating and trying to expand the languages, for people who do not speak English or do not want to use the translator. 😂😂😂

**Comment by masterking32** [comment]
Thats fine, I think I'm done now :D
